import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

// Pinned so the PDF bytes are identical on every seed run.
const PINNED_DATE = new Date("2025-01-01T00:00:00Z");

export type PdfLine =
  | { kind: "title"; text: string }
  | { kind: "heading"; text: string }
  | { kind: "text"; text: string }
  | { kind: "kv"; key: string; value: string }
  | { kind: "gap" };

/**
 * Render a simple single-column document. Deterministic: fixed fonts, fixed
 * metadata dates, no object streams, no random IDs.
 */
export async function renderPdf(lines: PdfLine[]): Promise<Uint8Array> {
  const doc = await PDFDocument.create({ updateMetadata: false });
  doc.setTitle(lines.find((l) => l.kind === "title")?.text ?? "Document");
  doc.setAuthor("Northwind Labs seed");
  doc.setProducer("crossfire-seed");
  doc.setCreator("crossfire-seed");
  doc.setCreationDate(PINNED_DATE);
  doc.setModificationDate(PINNED_DATE);

  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);

  const width = 612;
  const height = 792;
  const margin = 56;
  const maxWidth = width - margin * 2;
  let page = doc.addPage([width, height]);
  let y = height - margin;

  const ensure = (need: number) => {
    if (y - need < margin) {
      page = doc.addPage([width, height]);
      y = height - margin;
    }
  };

  const wrap = (text: string, f: typeof font, size: number): string[] => {
    const words = text.split(" ");
    const out: string[] = [];
    let cur = "";
    for (const w of words) {
      const trial = cur ? `${cur} ${w}` : w;
      if (f.widthOfTextAtSize(trial, size) > maxWidth && cur) {
        out.push(cur);
        cur = w;
      } else {
        cur = trial;
      }
    }
    if (cur) out.push(cur);
    return out;
  };

  for (const line of lines) {
    switch (line.kind) {
      case "title": {
        ensure(30);
        page.drawText(line.text, { x: margin, y: y - 20, size: 20, font: bold });
        y -= 34;
        break;
      }
      case "heading": {
        ensure(24);
        page.drawText(line.text, { x: margin, y: y - 13, size: 13, font: bold });
        y -= 22;
        break;
      }
      case "text": {
        for (const w of wrap(line.text, font, 10.5)) {
          ensure(15);
          page.drawText(w, { x: margin, y: y - 11, size: 10.5, font });
          y -= 15;
        }
        break;
      }
      case "kv": {
        ensure(16);
        page.drawText(line.key, { x: margin, y: y - 11, size: 10.5, font: bold });
        page.drawText(line.value, { x: margin + 150, y: y - 11, size: 10.5, font });
        y -= 16;
        break;
      }
      case "gap": {
        y -= 10;
        break;
      }
    }
  }

  // Thin footer rule on the first page for a document feel.
  const first = doc.getPage(0);
  first.drawLine({
    start: { x: margin, y: margin - 10 },
    end: { x: width - margin, y: margin - 10 },
    thickness: 0.5,
    color: rgb(0.6, 0.6, 0.6),
  });
  first.drawText("Generated by the Crossfire deterministic seed. Fictional data.", {
    x: margin,
    y: margin - 24,
    size: 8,
    font,
    color: rgb(0.45, 0.45, 0.45),
  });

  return doc.save({ useObjectStreams: false, addDefaultPage: false });
}
