// Fetches the row facts behind a sample that questions.ts needs to pick and
// fill a question template. Deterministic plain SQL, no LLM.
import { and, eq, ne, sql } from "drizzle-orm";
import { db, schema } from "@/db";
import type { SampleCandidate } from "./sampler";
import { monthOf, yearOf } from "./util";

// Counterparty names used by the seed for non-vendor bank rows (payroll,
// Dodo payouts, the bank's own fees/interest). Mirrors data generated by
// scripts/lib/generate.ts; kept local so this file has no dependency on it.
const KNOWN_NON_VENDOR_COUNTERPARTIES = new Set([
  "Dodo Payments",
  "Northwind Labs Payroll",
  "Coastal Trust Bank",
]);

export type InvoiceDetail = {
  kind: "invoice";
  invoiceNumber: string;
  vendorId: number;
  vendorName: string;
  amountCents: number;
  issueDate: string;
  approvedBy: string | null;
  contractRateCents: number | null;
  contractEffectiveTo: string | null;
  outsideContractTerm: boolean;
  hasSiblingInvoiceSameMonth: boolean;
};

export type BankDetail = {
  kind: "bank_transaction";
  reference: string;
  counterparty: string;
  description: string;
  amountCents: number;
  date: string;
  isKnownCounterparty: boolean;
  duplicateReferenceCount: number; // other bank rows sharing this reference
};

export type DodoDetail = {
  kind: "dodo_transaction";
  type: "payment" | "refund" | "dispute" | "payout";
  reference: string;
  customerId: string | null;
  amountCents: number;
  date: string;
};

export type SampleDetail = InvoiceDetail | BankDetail | DodoDetail;

export async function loadSampleDetail(candidate: SampleCandidate): Promise<SampleDetail> {
  if (candidate.sampleType === "invoice") return loadInvoiceDetail(candidate.sampleId);
  if (candidate.sampleType === "bank_transaction") return loadBankDetail(candidate.sampleId);
  return loadDodoDetail(candidate.sampleId);
}

async function loadInvoiceDetail(id: number): Promise<InvoiceDetail> {
  const [row] = await db.select().from(schema.invoices).where(eq(schema.invoices.id, id));
  if (!row) throw new Error(`invoice ${id} not found`);

  const [vendor] = await db.select().from(schema.vendors).where(eq(schema.vendors.id, row.vendorId));
  const contract = vendor?.contractId
    ? (await db.select().from(schema.contracts).where(eq(schema.contracts.id, vendor.contractId)))[0]
    : undefined;

  const [{ count }] = await db
    .select({ count: sql<number>`count(*)::int` })
    .from(schema.invoices)
    .where(
      and(
        eq(schema.invoices.vendorId, row.vendorId),
        ne(schema.invoices.id, row.id),
        sql`date_trunc('month', ${schema.invoices.issueDate}) = date_trunc('month', ${row.issueDate}::date)`,
      ),
    );

  const contractRateCents = contract ? Math.round(Number(contract.monthlyRate) * 100) : null;
  const outsideContractTerm = contract
    ? row.issueDate < contract.effectiveFrom || row.issueDate > contract.effectiveTo
    : false;

  return {
    kind: "invoice",
    invoiceNumber: row.invoiceNumber,
    vendorId: row.vendorId,
    vendorName: vendor?.name ?? `vendor #${row.vendorId}`,
    amountCents: Math.round(Number(row.amount) * 100),
    issueDate: row.issueDate,
    approvedBy: row.approvedBy,
    contractRateCents,
    contractEffectiveTo: contract?.effectiveTo ?? null,
    outsideContractTerm,
    hasSiblingInvoiceSameMonth: count > 0,
  };
}

async function loadBankDetail(id: number): Promise<BankDetail> {
  const [row] = await db.select().from(schema.bankTransactions).where(eq(schema.bankTransactions.id, id));
  if (!row) throw new Error(`bank_transaction ${id} not found`);

  const [{ count }] = await db
    .select({ count: sql<number>`count(*)::int` })
    .from(schema.bankTransactions)
    .where(and(eq(schema.bankTransactions.reference, row.reference), ne(schema.bankTransactions.id, row.id)));

  const [vendorMatch] = await db.select().from(schema.vendors).where(eq(schema.vendors.name, row.counterparty));
  const isKnownCounterparty = Boolean(vendorMatch) || KNOWN_NON_VENDOR_COUNTERPARTIES.has(row.counterparty);

  return {
    kind: "bank_transaction",
    reference: row.reference,
    counterparty: row.counterparty,
    description: row.description,
    amountCents: Math.round(Number(row.amount) * 100),
    date: row.date,
    isKnownCounterparty,
    duplicateReferenceCount: count,
  };
}

async function loadDodoDetail(id: number): Promise<DodoDetail> {
  const [row] = await db.select().from(schema.dodoTransactions).where(eq(schema.dodoTransactions.id, id));
  if (!row) throw new Error(`dodo_transaction ${id} not found`);

  return {
    kind: "dodo_transaction",
    type: row.type,
    reference: row.reference,
    customerId: row.customerId,
    amountCents: Math.round(Number(row.amount) * 100),
    date: row.date,
  };
}

// Re-exported so callers (questions.ts) can label a month without importing util directly.
export function monthYearLabel(date: string): string {
  const MONTH_NAMES = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December",
  ];
  return `${MONTH_NAMES[monthOf(date) - 1]} ${yearOf(date)}`;
}
